# Build settings
markdown: kramdown
permalink: pretty
sass:
  sass_dir: _scss
  style: compressed

# hack to build thumbnail link
thumbURL: "/assets/i/"

# publisher metadata
author: Ian Kilby
author_description: The story of a guy who reversed his type-2 diabetes.

gems: [jekyll-paginate, jekyll-gist]

paginate: 4

paginate_limit: 4

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: reversemydiabetes



