# Build settings
markdown: kramdown
permalink: pretty
sass:
  sass_dir: _scss
  style: compressed


gems: [jekyll-paginate, jekyll-gist]

paginate: 10

paginate_limit: 10

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: dug


